### ISSUE TITLE
check the validations

### ISSUE THREAD

**Issue by rvsp** [sourabhrajwade/GUVI-Full_Stack_Developer_BootCamp#5]
even all fields data are entered form is invalid

https://github.com/sourabhrajwade/GUVI-Full_Stack_Developer_BootCamp/blob/d5efc534ed37210df636b852db0857339e9314cc/Day-30/ReactiveForms/src/app/app.component.html#L57

**Comment by sourabhrajwade** [comment]
Checked all the fields. Now it is working.
